services:
  lavalink:
    image: fredboat/lavalink:4.0.8
    environment:
      - _JAVA_OPTIONS=-Xmx1600M  # Java එකට 1.6GB වෙන් කරනවා, ඉතුරු ටික container overhead එකට
    deploy:
      resources:
        limits:
          memory: 2048M # උඹේ 2GB limit එක මෙතන තියෙනවා
    volumes:
      - ../files/lavalink/application.yml:/opt/Lavalink/application.yml
    networks:
      - dokploy-network

  static-site:
    image: nginx:alpine
    volumes:
      - ../files/site-content:/usr/share/nginx/html # උඹේ html files මෙතනට දාපන්
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
