services:
  lavalink:
    image: fredboat/lavalink:4.0.8
    environment:
      - _JAVA_OPTIONS=-Xmx1600M
    deploy:
      resources:
        limits:
          memory: 2048M
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml # application.yml එක root එකේ තියෙන්න ඕනේ
    ports:
      - "2333:2333"

  static-site:
    image: nginx:alpine
    # Ports අයින් කළා මොකද Dokploy Proxy එකත් එක්ක Conflict වෙන නිසා
    volumes:
      - ./web:/usr/share/nginx/html # 'web' folder එක repository එකේ තියෙන්නම ඕනේ
